#!/usr/bin/env bats

load test_helper

setup() {
  source ./lib/new/new.sh
  rm -rf testing && mkdir testing
  cd testing
}

teardown() {
  cd ..
  rm -rf testing
}

@test "it creates the base directories of a Ruby workspace" {
  create_base_directories testrb

  [ -d "./testrb/" ]
  [ -d "./testrb/lib/" ]
  [ -d "./testrb/config/" ]
  [ -d "./testrb/test/" ]
}

@test "it creates .gitignore file with contents" {
  create_gitignore_file

  [ -e "./.gitignore" ]
  [ "$(head -n 1 .gitignore)" = "# Generated by buildr CLI" ]
}

@test "it creates Gemfile file with contents" {
  create_gemfile_file

  [ -e "./Gemfile" ]
  [ "$(head -n 1 Gemfile)" = "source \"https://rubygems.org\"" ]
}

@test "it creates Rakefile file with contents" {
  create_rakefile_file

  [ -e "./Rakefile" ]
  [ "$(head -n 1 Rakefile)" = "require 'rake'" ]
}

@test "it creates README file with contents" {
  create_readme_file testrb

  [ -e "./README.md" ]
  [ "$(head -n 1 README.md)" = "# testrb README" ]
}

@test "it creates test_helper file with contents" {
  create_test_helper_file

  [ -e "./test_helper.rb" ]
  [ "$(head -n 1 test_helper.rb)" = "require 'minitest/autorun'" ]
}
