#!/bin/bash

execute_new_command() {
  if [ "$1" = "" ]; then
    echo "Error: A project name must be given after the command 'new'"
    exit 1
  else
    echo "Building workspace for project '${1}'"
  fi
}

create_base_directories() {
  mkdir $1
  mkdir {$1/config,$1/lib,$1/test}
  touch $1/config/.keep && touch $1/lib/.keep
}

create_gitignore_file() {
  touch .gitignore
  printf "%s\n" "# Generated by buildr CLI" "" "# Bundler generated files" "/.bundle/" \
                "" "/tmp/" > .gitignore
}

create_gemfile_file() {
  touch Gemfile
  printf "%s\n" "source \"https://rubygems.org\"" "" "gem 'pry'" "gem 'rake'" \
                "" "group :test do" "  gem 'minitest'" "end" > Gemfile
}

create_rakefile_file() {
  touch Rakefile
  printf "%s\n" "require 'rake'" "" "namespace :test do" \
                "  desc 'Run all tests in test suite'" "  task :all do" \
                "    Dir.glob('./test/*_test.rb').each { |file| require file}" "  end" \
                "end" > Rakefile
}

create_readme_file() {
  touch README.md
  printf "%s\n" "# $1 README" "" "Generated by buildr." "Under construction." > README.md
}

create_test_helper_file() {
  touch test_helper.rb
  printf "%s\n" "require 'minitest/autorun'" "require 'minitest/pride'" "require 'pry'" \
                "" "PATH = File.expand_path('.')" "ENV['test'] = 'true'" > test_helper.rb
}